const ComponentTypes = {
  IMAGE: 'Image',
  PANEL: 'Panel',
  TEXT: 'Text',
  INPUT: 'Input',
  BUTTON: 'Button',
  ICON: 'Icon',
  TABLE: 'Table',
  TABLE_HEAD: 'TableHead',
  TABLE_HEAD_CELL: 'TableHeadCell',
  TABLE_BODY: 'TableBody',
  TABLE_CELL: 'TableCell',
  TABLE_FOOT: 'TableFoot',
  TABLE_ROW: 'TableRow',
  LINK: 'Link',
  SELECT: 'Select',
  INPUT_INTEGER: 'InputInteger',
  INPUT_DECIMAL: 'InputDecimal',
  INPUT_BOOLEAN: 'InputBoolean',
  INPUT_DATE: 'InputDate',
  INPUT_PASSWORD: 'InputPassword',
  INPUT_TEXTAREA: 'InputTextArea',
  FILE_UPLOAD: 'FileUpload',
  INPUT_RADIO: 'InputRadio',
};

export default ComponentTypes;
